owner: SCN-KY 
repo: SCN-Status 
skipDeleteIssues: true
user-agent: upptime-bot

sites:
  - name: Main Site
    url: https://www.starlightcommunity.network
    icon: https://static.wixstatic.com/media/12679b_f990c0dfc4744a7d828199dd2c91ea50~mv2.png
  - name: Fallback Site
    url: https://fallback.starlightcommunity.network
  - name: Classic Site
    url: https://classic.starlightcommunity.network
  - name: Support Forum
    url: https://support.starlightcommunity.network
    icon: https://static.wixstatic.com/media/12679b_f990c0dfc4744a7d828199dd2c91ea50~mv2.png
  - name: Scumcraft
    check: "tcp-ping"
    url: scumcraft.starlightcommunity.net
    port: 55294
    icon: https://static.wixstatic.com/media/2d311a_ff5d4c5be50b4692a391da67869d1b95~mv2.png
  - name: Collin3DModels
    url: https://collin3dmodels.com

status-website:
  cname: status.starlightcommunity.network
  themeUrl: https://status.starlightcommunity.network/dark.css
  logoUrl: https://static.wixstatic.com/media/af0f76_efa09e38ca6b4e30ad3616f0a632b1b6~mv2.png
  favicon: https://static.wixstatic.com/media/af0f76_efa09e38ca6b4e30ad3616f0a632b1b6~mv2.png
  name: Starlight Community Network
  introTitle: "**Welcome** to the Starlight Community Network Status Page."
  introMessage: When one of our Sites/Services Goes down you'll know here!
  metaTags:
    - name: "theme-color"
      content: "#874fbf" 
    - name: "og:site_name"
      content: "SCN Status - Powered By Upptime"
    - name: "og:type"
      content: "website" 
    - name: "og:title"
      content: "Starlight Community Network | Status"
    - name: "og:description"
      content: "Stay informed with real-time updates on our service status. Check for outages, scheduled maintenance, and performance metrics to ensure seamless connectivity."
    - name: "og:image"
      content: "https://static.wixstatic.com/media/af0f76_efa09e38ca6b4e30ad3616f0a632b1b6~mv2.png"
  navbar:
    - title: Status
      href: /
    - title: Main Site
      href: https://www.starlightcommunity.network
    - title: Fallback Site
      href: https://fallback.starlightcommunity.network
  robotsText: "User-agent: Googlebot \n Disallow: /"
