# Change these first
owner: Starlight-Community-Network # Your GitHub organization or username, where this repository lives
repo: status.starlightgaming.network # The name of this repository
skipDeleteIssues: true
user-agent: upptime-bot

sites:
  - name: Starlight Community Network
    url: https://www.starlightcommunity.network
  - name: Fallback Site
    url: https://fallback.starlightcommunity.network
  - name: Classic Site
    url: https://classic.starlightcommunity.network
  - name: Clonn's SMP
    check: "tcp-ping"
    url: smp.starlightcommunity.net
    port: 55294
    icon: https://static.wixstatic.com/media/2d311a_ff5d4c5be50b4692a391da67869d1b95~mv2.png
  - name: Photon Tweaks
    url: https://photontweaks.starlightcommunity.net
  - name: Roguenight Transportation CAD (Closed)
    url: https://rntcad.starlightcommunity.net
    icon: https://static.wixstatic.com/media/2d311a_3ed098df00c4427e974febe5f3830c59~mv2.png
  - name: Blossom Rabbit lounge
    url: https://Blossom.starlightcommunity.net
  - name: BRCRP CAD (Kind of don't do nothing)
    url: https://brcad.starlightcommunity.net
  - name: BRCRP Server & Admin Panel (To return)
    url: http://brcrp.starlightcommunity.net
    expectedStatusCodes:
      - 0
    icon: https://static.wixstatic.com/media/af0f76_b53a5d44505f43d1baa34c3565a4bd82~mv2.png
  - name: FluffyxGaming (To Be Removed Visit URL Gor More Info)
    url: http://fluffyx.starlightgaming.network
  - name: Collin3DModels
    url: https://www.collin3dmodels.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.starlightcommunity.network
  theme: night
  logoUrl: https://static.wixstatic.com/media/af0f76_efa09e38ca6b4e30ad3616f0a632b1b6~mv2.png
  favicon: https://static.wixstatic.com/media/af0f76_efa09e38ca6b4e30ad3616f0a632b1b6~mv2.png
  name: Starlight Community Network
  introTitle: "**Welcome** to the Starlight Community Network Status Page."
  introMessage: When one of our Sites/Services Goes down you'll know here!
  metaTags:
    - name: "theme-color"
      content: "#874fbf" 
    - name: "og:site_name"
      content: "Starlight Community Network Powered By Upptime"
    - name: "og:type"
      content: "website" 
    - name: "og:title"
      content: "Starlight Community Network | Status"
    - name: "og:description"
      content: "Stay informed with real-time updates on our service status. Check for outages, scheduled maintenance, and performance metrics to ensure seamless connectivity."
    - name: "og:image"
      content: "https://static.wixstatic.com/media/af0f76_efa09e38ca6b4e30ad3616f0a632b1b6~mv2.png"
  navbar:
    - title: Status
      href: /
    - title: Main Site
      href: https://www.starlightcommunity.network
    - title: Fallback Site
      href: https://fallback.starlightcommunity.network
    - title: MS Status page
      href: https://upptime.moonlightsimulations.org
      status-website:
  robotsText: "User-agent: Googlebot \n Disallow: /"
