# Change these first
owner: Starlight-Community-Network # Your GitHub organization or username, where this repository lives
repo: Status.starlightgaming.network # The name of this repository

sites:
  - name: Starlight Community Network
    url: https://www.starlightgaming.network
  - name: Fallback Site
    url: https://fallback.starlightgaming.network
  - name: Classic Site
    url: https://classic.starlightgaming.network
  - name: Photon Tweaks
    url: https://photontweaks.starlightgaming.network/ 
  - name: Roguenight Transportation CAD
    url: https://rntcad.starlightgaming.network/
    icon: https://static.wixstatic.com/media/2d311a_3ed098df00c4427e974febe5f3830c59~mv2.png
  - name: Blossom Rabbit lounge
    url: https://Blossom.starlightgaming.network
  - name: BRCRP CAD
    url: https://brcrpcad.hamz.pro/
  - name: BRCRP Server
    url: http://brcrp.starlightgaming.net:3009
    icon: https://static.wixstatic.com/media/af0f76_b53a5d44505f43d1baa34c3565a4bd82~mv2.png
  - name: BRCRP Admin Panel
    url: http://brcrp.starlightgaming.net:3027
    icon: http://brcrp.starlightgaming.net:3027/favicon_default.svg
  - name: FluffyxGaming
    url: https://fluffyx.starlightgaming.network/
  - name: Collin3DModels
    url: https://www.collin3dmodels.com/
    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.starlightgaming.network
  theme: night
  logoUrl: https://static.wixstatic.com/media/af0f76_efa09e38ca6b4e30ad3616f0a632b1b6~mv2.png
  favicon: https://static.wixstatic.com/media/af0f76_efa09e38ca6b4e30ad3616f0a632b1b6~mv2.png
  name: Starlight Community Network
  metaTags:
    - name: "theme-color"
  content: "#874fbf"
    - name: "og:site_name"
  content: "Starlight Community Network | Status"
    - name: "og:type"
  content: "website" 
    - name: "og:title"
  content: "SCN | Downtime"
    - name: "og:description"
  content: "Stay informed with real-time updates on our service status. Check for outages, scheduled maintenance, and performance metrics to ensure seamless connectivity."
    - name: "og:image"
  content: "https://static.wixstatic.com/media/af0f76_efa09e38ca6b4e30ad3616f0a632b1b6~mv2.png"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

#introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
#introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
